# Generated by Django 6.0.3 on 2026-04-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jewelry', 'Jewelry'), ('home-decor', 'Home Decor'), ('textiles', 'Textiles'), ('pottery', 'Pottery'), ('bags', 'Bags & Accessories'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
